// One-time migration/seed: backfills the legacy Terms & Conditions document
// with `type: 'terms'`, and inserts a starter Privacy Policy document so the
// new /api/legal/privacy endpoint has content to serve.
//
// Run with: node scripts/seedPrivacyPolicy.js
require('dotenv').config();
const mongoose = require('mongoose');
const LegalContent = require('../models/LegalContent');

const PRIVACY_SECTIONS = [
  {
    order: 1,
    title: 'Information We Collect',
    body: 'We collect information you provide directly (name, email, phone number, M-Pesa details) and information generated by using Tumwa (errand history, location data while an errand is active, and device identifiers).',
  },
  {
    order: 2,
    title: 'How We Use Information',
    body: 'We use your information to match errands with runners, process M-Pesa payments, verify runner identity, provide customer support, and improve the safety and reliability of the platform.',
  },
  {
    order: 3,
    title: 'Information Sharing',
    body: 'We share only what is necessary to complete an errand — your name, phone number, and delivery address are shared with the runner or customer assigned to that errand. We do not sell your personal information.',
  },
  {
    order: 4,
    title: 'Data Security',
    body: 'Payment credentials are never stored on our servers — all M-Pesa transactions are processed directly through Safaricom\'s Daraja API. Passwords are hashed and sensitive account fields are encrypted at rest.',
  },
  {
    order: 5,
    title: 'Your Rights',
    body: 'You can request a copy of your data, ask us to correct inaccurate information, or request account deletion at any time by contacting support through the Help Center.',
  },
];

async function run() {
  await mongoose.connect(process.env.MONGO_URI);

  const backfill = await LegalContent.updateMany(
    { type: { $exists: false } },
    { $set: { type: 'terms' } },
  );
  console.log(`Backfilled ${backfill.modifiedCount} legacy document(s) to type: 'terms'`);

  const existingPrivacy = await LegalContent.findOne({ type: 'privacy' });
  if (existingPrivacy) {
    console.log('Privacy policy document already exists — skipping seed');
  } else {
    await LegalContent.create({
      type: 'privacy',
      content: '',
      sections: PRIVACY_SECTIONS,
    });
    console.log('Seeded Privacy Policy document');
  }

  await mongoose.connection.close();
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
